/* eslint-disable @typescript-eslint/naming-convention */
export const viewsData: Array<string> = ['Day', 'Week', 'Month'];

export const agencysData: Record<string, any>[] = [
    {
        Name: 'Anaisha Sharma',
        Gender: 'Female',
        city: 'Ahmedabad',
        Text: 'user',
        Id: 1,
        DepartmentId: 1,
        Color: '#ea7a57',
        Education: 'MBBS, DMRD',
        Specialization: 'generalmedicine',
        Experience: '10+ years',
        Designation: 'Hosptial',
        DutyTiming: 'Shift1',
        Email: 'AnaishaSharma@sample.com',
        Mobile: '+91 000 000 0000',
        Availability: 'busy',
        StartHour: '08:00',
        EndHour: '17:00',
        AvailableDays: [0, 2, 3, 4, 5],
        WorkDays: [
            {
                Day: 'sunday',
                Index: 0,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 1, 8, 0),
                WorkEndHour: new Date(2022, 7, 1, 17, 0),
                BreakStartHour: new Date(2022, 7, 1, 12, 0),
                BreakEndHour: new Date(2022, 7, 1, 13, 0),
                State: 'AddBreak',
            },
            {
                Day: 'monday',
                Index: 1,
                Enable: false,
                WorkStartHour: new Date(2022, 7, 2, 8, 0),
                WorkEndHour: new Date(2022, 7, 2, 17, 0),
                BreakStartHour: new Date(2022, 7, 2, 12, 0),
                BreakEndHour: new Date(2022, 7, 2, 13, 0),
                State: 'TimeOff',
            },
            {
                Day: 'tuesday',
                Index: 2,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 3, 8, 0),
                WorkEndHour: new Date(2022, 7, 3, 17, 0),
                BreakStartHour: new Date(2022, 7, 3, 12, 0),
                BreakEndHour: new Date(2022, 7, 3, 13, 0),
                State: 'AddBreak',
            },
            {
                Day: 'wednesday',
                Index: 3,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 4, 8, 0),
                WorkEndHour: new Date(2022, 7, 4, 17, 0),
                BreakStartHour: new Date(2022, 7, 4, 12, 0),
                BreakEndHour: new Date(2022, 7, 4, 13, 0),
                State: 'AddBreak',
            },
            {
                Day: 'thursday',
                Index: 4,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 5, 8, 0),
                WorkEndHour: new Date(2022, 7, 5, 17, 0),
                BreakStartHour: new Date(2022, 7, 5, 12, 0),
                BreakEndHour: new Date(2022, 7, 5, 13, 0),
                State: 'AddBreak',
            },
            {
                Day: 'friday',
                Index: 5,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 6, 8, 0),
                WorkEndHour: new Date(2022, 7, 6, 17, 0),
                BreakStartHour: new Date(2022, 7, 6, 12, 0),
                BreakEndHour: new Date(2022, 7, 6, 13, 0),
                State: 'RemoveBreak',
            },
            {
                Day: 'saturday',
                Index: 6,
                Enable: false,
                WorkStartHour: new Date(2022, 7, 7, 8, 0),
                WorkEndHour: new Date(2022, 7, 7, 17, 0),
                BreakStartHour: new Date(2022, 7, 7, 12, 0),
                BreakEndHour: new Date(2022, 7, 7, 13, 0),
                State: 'TimeOff'
            }
        ]
    },
    {
        Name: 'Grow Self',
        Gender: 'Female',
        city: 'Chennai',
        Text: 'user',
        Id: 2,
        DepartmentId: 2,
        Color: '#7fa900',
        Education: 'CA, ACCA',
        Specialization: 'CA, ACCA',
        Experience: '2+ years',
        Designation: 'Finance Advice',
        Email: 'mollie65@rpy.com',
        DutyTiming: 'Shift2',
        Mobile: '+91 000 000 0000',
        Availability: 'available',
        StartHour: '10:00',
        EndHour: '19:00',
        AvailableDays: [0, 1, 2, 3, 4],
        WorkDays: [
            {
                Day: 'sunday',
                Index: 0,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 1, 10, 0),
                WorkEndHour: new Date(2022, 7, 1, 19, 0),
                BreakStartHour: new Date(2022, 7, 1, 14, 0),
                BreakEndHour: new Date(2022, 7, 1, 15, 0),
                State: 'AddBreak',
            },
            {
                Day: 'monday',
                Index: 1,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 2, 10, 0),
                WorkEndHour: new Date(2022, 7, 2, 19, 0),
                BreakStartHour: new Date(2022, 7, 2, 14, 0),
                BreakEndHour: new Date(2022, 7, 2, 15, 0),
                State: 'RemoveBreak',
            },
            {
                Day: 'tuesday',
                Index: 2,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 3, 10, 0),
                WorkEndHour: new Date(2022, 7, 3, 19, 0),
                BreakStartHour: new Date(2022, 7, 3, 14, 0),
                BreakEndHour: new Date(2022, 7, 3, 15, 0),
                State: 'AddBreak',
            },
            {
                Day: 'wednesday',
                Index: 3,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 4, 10, 0),
                WorkEndHour: new Date(2022, 7, 4, 19, 0),
                BreakStartHour: new Date(2022, 7, 4, 14, 0),
                BreakEndHour: new Date(2022, 7, 4, 15, 0),
                State: 'AddBreak',
            },
            {
                Day: 'thursday',
                Index: 4,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 5, 10, 0),
                WorkEndHour: new Date(2022, 7, 5, 19, 0),
                BreakStartHour: new Date(2022, 7, 5, 14, 0),
                BreakEndHour: new Date(2022, 7, 5, 15, 0),
                State: 'RemoveBreak',
            },
            {
                Day: 'friday',
                Index: 5,
                Enable: false,
                WorkStartHour: new Date(2022, 7, 6, 10, 0),
                WorkEndHour: new Date(2022, 7, 6, 19, 0),
                BreakStartHour: new Date(2022, 7, 6, 14, 0),
                BreakEndHour: new Date(2022, 7, 6, 15, 0),
                State: 'TimeOff',
            },
            {
                Day: 'saturday',
                Index: 6,
                Enable: false,
                WorkStartHour: new Date(2022, 7, 7, 10, 0),
                WorkEndHour: new Date(2022, 7, 7, 19, 0),
                BreakStartHour: new Date(2022, 7, 7, 14, 0),
                BreakEndHour: new Date(2022, 7, 7, 15, 0),
                State: 'TimeOff'
            }
        ]
    },
    {
        Name: 'Yaraana',
        Gender: 'Female',
        city: 'Mumbai',
        Text: 'user',
        Id: 3,
        DepartmentId: 7,
        Color: '#fec200',
        Education: 'LLB',
        Specialization: 'law',
        Experience: '8+ years',
        Designation: 'Legal Specialist',
        DutyTiming: 'Shift3',
        Email: 'yara105@sample.com',
        Mobile: '+91 000 000 0000',
        Availability: 'away',
        StartHour: '12:00',
        EndHour: '21:00',
        AvailableDays: [1, 2, 3, 4, 5],
        WorkDays: [
            {
                Day: 'sunday',
                Index: 0,
                Enable: false,
                WorkStartHour: new Date(2022, 7, 1, 12, 0),
                WorkEndHour: new Date(2022, 7, 1, 21, 0),
                BreakStartHour: new Date(2022, 7, 1, 16, 0),
                BreakEndHour: new Date(2022, 7, 1, 17, 0),
                State: 'TimeOff',
            },
            {
                Day: 'monday',
                Index: 1,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 2, 12, 0),
                WorkEndHour: new Date(2022, 7, 2, 21, 0),
                BreakStartHour: new Date(2022, 7, 2, 16, 0),
                BreakEndHour: new Date(2022, 7, 2, 17, 0),
                State: 'AddBreak',
            },
            {
                Day: 'tuesday',
                Index: 2,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 3, 12, 0),
                WorkEndHour: new Date(2022, 7, 3, 21, 0),
                BreakStartHour: new Date(2022, 7, 3, 16, 0),
                BreakEndHour: new Date(2022, 7, 3, 17, 0),
                State: 'AddBreak',
            },
            {
                Day: 'wednesday',
                Index: 3,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 4, 12, 0),
                WorkEndHour: new Date(2022, 7, 4, 21, 0),
                BreakStartHour: new Date(2022, 7, 4, 16, 0),
                BreakEndHour: new Date(2022, 7, 4, 17, 0),
                State: 'AddBreak',
            },
            {
                Day: 'thursday',
                Index: 4,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 5, 12, 0),
                WorkEndHour: new Date(2022, 7, 5, 21, 0),
                BreakStartHour: new Date(2022, 7, 5, 16, 0),
                BreakEndHour: new Date(2022, 7, 5, 17, 0),
                State: 'AddBreak',
            },
            {
                Day: 'friday',
                Index: 5,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 6, 12, 0),
                WorkEndHour: new Date(2022, 7, 6, 21, 0),
                BreakStartHour: new Date(2022, 7, 6, 16, 0),
                BreakEndHour: new Date(2022, 7, 6, 17, 0),
                State: 'RemoveBreak',
            },
            {
                Day: 'saturday',
                Index: 6,
                Enable: false,
                WorkStartHour: new Date(2022, 7, 7, 12, 0),
                WorkEndHour: new Date(2022, 7, 7, 21, 0),
                BreakStartHour: new Date(2022, 7, 7, 16, 0),
                BreakEndHour: new Date(2022, 7, 7, 17, 0),
                State: 'TimeOff'
            }
        ]
    },
    {
        Name: 'Heal',
        Gender: 'Male',
        city: 'Delhi',
        Text: 'user',
        Id: 4,
        DepartmentId: 8,
        Color: '#865fcf',
        Education: 'Psychiatrist',
        Designation: 'Psychiatry Service',
        Specialization: 'Psychiatrist',
        Experience: '10+ years',
        DutyTiming: 'Shift1',
        Email: 'heal@mail.com',
        Mobile: '+91 000 000 0000',
        Availability: 'busy',
        StartHour: '08:00',
        EndHour: '17:00',
        AvailableDays: [2, 3, 4, 5, 6],
        WorkDays: [
            {
                Day: 'sunday',
                Index: 0,
                Enable: false,
                WorkStartHour: new Date(2022, 7, 1, 8, 0),
                WorkEndHour: new Date(2022, 7, 1, 17, 0),
                BreakStartHour: new Date(2022, 7, 1, 12, 0),
                BreakEndHour: new Date(2022, 7, 1, 13, 0),
                State: 'TimeOff',
            },
            {
                Day: 'monday',
                Index: 1,
                Enable: false,
                WorkStartHour: new Date(2022, 7, 2, 8, 0),
                WorkEndHour: new Date(2022, 7, 2, 17, 0),
                BreakStartHour: new Date(2022, 7, 2, 12, 0),
                BreakEndHour: new Date(2022, 7, 2, 13, 0),
                State: 'TimeOff',
            },
            {
                Day: 'tuesday',
                Index: 2,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 3, 8, 0),
                WorkEndHour: new Date(2022, 7, 3, 17, 0),
                BreakStartHour: new Date(2022, 7, 3, 12, 0),
                BreakEndHour: new Date(2022, 7, 3, 13, 0),
                State: 'AddBreak',
            },
            {
                Day: 'wednesday',
                Index: 3,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 4, 8, 0),
                WorkEndHour: new Date(2022, 7, 4, 17, 0),
                BreakStartHour: new Date(2022, 7, 4, 12, 0),
                BreakEndHour: new Date(2022, 7, 4, 13, 0),
                State: 'AddBreak',
            },
            {
                Day: 'thursday',
                Index: 4,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 5, 8, 0),
                WorkEndHour: new Date(2022, 7, 5, 17, 0),
                BreakStartHour: new Date(2022, 7, 5, 12, 0),
                BreakEndHour: new Date(2022, 7, 5, 13, 0),
                State: 'AddBreak',
            },
            {
                Day: 'friday',
                Index: 5,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 6, 8, 0),
                WorkEndHour: new Date(2022, 7, 6, 17, 0),
                BreakStartHour: new Date(2022, 7, 6, 12, 0),
                BreakEndHour: new Date(2022, 7, 6, 13, 0),
                State: 'RemoveBreak',
            },
            {
                Day: 'saturday',
                Index: 6,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 7, 8, 0),
                WorkEndHour: new Date(2022, 7, 7, 17, 0),
                BreakStartHour: new Date(2022, 7, 7, 12, 0),
                BreakEndHour: new Date(2022, 7, 7, 13, 0),
                State: 'AddBreak'
            }
        ]
    },
    {
        Name: 'Edwards',
        Gender: 'Female',
        city: 'Bengaluru',
        Text: 'user',
        Id: 5,
        DepartmentId: 2,
        Color: '#1aaa55',
        Education: 'CA, ACCA',
        Designation: 'Life and Finance Security',
        Specialization: 'CA, ACCA',
        Experience: '10+ years',
        DutyTiming: 'Shift2',
        Email: 'amelia101@rpy.com',
        Mobile: '+91 000 000 0000',
        Availability: 'available',
        StartHour: '10:00',
        EndHour: '19:00',
        AvailableDays: [0, 2, 3, 4, 5],
        WorkDays: [
            {
                Day: 'sunday',
                Index: 0,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 1, 10, 0),
                WorkEndHour: new Date(2022, 7, 1, 19, 0),
                BreakStartHour: new Date(2022, 7, 1, 14, 0),
                BreakEndHour: new Date(2022, 7, 1, 15, 0),
                State: 'AddBreak',
            },
            {
                Day: 'monday',
                Index: 1,
                Enable: false,
                WorkStartHour: new Date(2022, 7, 2, 10, 0),
                WorkEndHour: new Date(2022, 7, 2, 19, 0),
                BreakStartHour: new Date(2022, 7, 2, 14, 0),
                BreakEndHour: new Date(2022, 7, 2, 15, 0),
                State: 'TimeOff',
            },
            {
                Day: 'tuesday',
                Index: 2,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 3, 10, 0),
                WorkEndHour: new Date(2022, 7, 3, 19, 0),
                BreakStartHour: new Date(2022, 7, 3, 14, 0),
                BreakEndHour: new Date(2022, 7, 3, 15, 0),
                State: 'AddBreak',
            },
            {
                Day: 'wednesday',
                Index: 3,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 4, 10, 0),
                WorkEndHour: new Date(2022, 7, 4, 19, 0),
                BreakStartHour: new Date(2022, 7, 4, 14, 0),
                BreakEndHour: new Date(2022, 7, 4, 15, 0),
                State: 'AddBreak',
            },
            {
                Day: 'thursday',
                Index: 4,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 5, 10, 0),
                WorkEndHour: new Date(2022, 7, 5, 19, 0),
                BreakStartHour: new Date(2022, 7, 5, 14, 0),
                BreakEndHour: new Date(2022, 7, 5, 15, 0),
                State: 'AddBreak',
            },
            {
                Day: 'friday',
                Index: 5,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 6, 10, 0),
                WorkEndHour: new Date(2022, 7, 6, 19, 0),
                BreakStartHour: new Date(2022, 7, 6, 14, 0),
                BreakEndHour: new Date(2022, 7, 6, 15, 0),
                State: 'RemoveBreak',
            },
            {
                Day: 'saturday',
                Index: 6,
                Enable: false,
                WorkStartHour: new Date(2022, 7, 7, 10, 0),
                WorkEndHour: new Date(2022, 7, 7, 19, 0),
                BreakStartHour: new Date(2022, 7, 7, 14, 0),
                BreakEndHour: new Date(2022, 7, 7, 15, 0),
                State: 'TimeOff'
            }
        ]
    },
    {
        Name: 'Live Long',
        Gender: 'Female',
        city: 'Ahmedabad',
        Text: 'user',
        Id: 6,
        DepartmentId: 1,
        Color: '#df5286',
        Education: 'MD, DM, FACC, FICC',
        Designation: 'Hospital',
        Specialization: 'generalmedicine',
        Experience: '1+ years',
        DutyTiming: 'Shift2',
        Email: 'alexa55@sample.com',
        Mobile: '+91 000 000 0000',
        Availability: 'busy',
        StartHour: '10:00',
        EndHour: '19:00',
        AvailableDays: [2, 3, 4, 5, 6],
        WorkDays: [
            {
                Day: 'sunday',
                Index: 0,
                Enable: false,
                WorkStartHour: new Date(2022, 7, 1, 10, 0),
                WorkEndHour: new Date(2022, 7, 1, 19, 0),
                BreakStartHour: new Date(2022, 7, 1, 14, 0),
                BreakEndHour: new Date(2022, 7, 1, 15, 0),
                State: 'TimeOff',
            },
            {
                Day: 'monday',
                Index: 1,
                Enable: false,
                WorkStartHour: new Date(2022, 7, 2, 10, 0),
                WorkEndHour: new Date(2022, 7, 2, 19, 0),
                BreakStartHour: new Date(2022, 7, 2, 14, 0),
                BreakEndHour: new Date(2022, 7, 2, 15, 0),
                State: 'TimeOff',
            },
            {
                Day: 'tuesday',
                Index: 2,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 3, 10, 0),
                WorkEndHour: new Date(2022, 7, 3, 19, 0),
                BreakStartHour: new Date(2022, 7, 3, 14, 0),
                BreakEndHour: new Date(2022, 7, 3, 15, 0),
                State: 'AddBreak',
            },
            {
                Day: 'wednesday',
                Index: 3,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 4, 10, 0),
                WorkEndHour: new Date(2022, 7, 4, 19, 0),
                BreakStartHour: new Date(2022, 7, 4, 14, 0),
                BreakEndHour: new Date(2022, 7, 4, 15, 0),
                State: 'AddBreak',
            },
            {
                Day: 'thursday',
                Index: 4,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 5, 10, 0),
                WorkEndHour: new Date(2022, 7, 5, 19, 0),
                BreakStartHour: new Date(2022, 7, 5, 14, 0),
                BreakEndHour: new Date(2022, 7, 5, 15, 0),
                State: 'AddBreak',
            },
            {
                Day: 'friday',
                Index: 5,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 6, 10, 0),
                WorkEndHour: new Date(2022, 7, 6, 19, 0),
                BreakStartHour: new Date(2022, 7, 6, 14, 0),
                BreakEndHour: new Date(2022, 7, 6, 15, 0),
                State: 'RemoveBreak',
            },
            {
                Day: 'saturday',
                Index: 6,
                Enable: true,
                WorkStartHour: new Date(2022, 7, 7, 10, 0),
                WorkEndHour: new Date(2022, 7, 7, 19, 0),
                BreakStartHour: new Date(2022, 7, 7, 14, 0),
                BreakEndHour: new Date(2022, 7, 7, 15, 0),
                State: 'AddBreak'
            }
        ]
    },
    
];

export const usersData: Record<string, any>[] = [
    {
        Id: 1,
        Name: 'Aayansh',
        Text: 'Aayansh',
        DOB: new Date(2000, 8, 3),
        Mobile: '+91 0000000000',
        Email: 'aayansh@mail.com',
        Address: 'Address Line 1, City, Country',
        enite: 'Monday',
        DepartmentName: 'GENERAL',
        BloodGroup: 'O+',
        Gender: 'Male',
        Notes: 'Medical Assistance'
    },
    {
        Id: 2,
        Name: 'Dhruv',
        Text: 'Dhruv',
        DOB: new Date(2000, 3, 5),
        Mobile: '+91 0000000000',
        Email: 'dhruv401@sample.com',
        Address: 'Address Line 1, City, Country',
        enite: 'Wednesday',
        DepartmentName: 'financeAdvisor',
        BloodGroup: 'AB+',
        Gender: 'Male',
        Notes: 'Finance Assistance',
    },
    {
        Id: 3,
        Name: 'Raghav',
        Text: 'Raghav',
        DOB: new Date(1985, 2, 3),
        Mobile: '+91 0000000000',
        Email: 'Raghav89@rpy.com',
        Address: 'Address Line 1, City, Country',
        enite: 'Monday',
        DepartmentName: 'financeAdvisor',
        BloodGroup: 'B+',
        Gender: 'Male',
        Notes: 'Finance Assistance',
    },
    {
        Id: 4,
        Name: 'Jannat',
        Text: 'Jannat',
        DOB: new Date(2000, 7, 3),
        Mobile: '+91 0000000000',
        Email: 'jannat@rpy.com',
        Address: 'Address Line 1, City, Country',
        enite: 'Monday',
        DepartmentName: 'financeAdvisor',
        BloodGroup: 'B+',
        Gender: 'Female',
        Notes: 'Finance Assistance',
    },
    {
        Id: 5,
        Name: 'Lalitha',
        Text: 'Lalitha',
        DOB: new Date(2005, 4, 29),
        Mobile: '+91 0000000000',
        Email: 'Lalitha60@sample.com',
        Address: 'Address Line 1, City, Country',
        enite: 'Monday',
        DepartmentName: 'generalmedicine',
        BloodGroup: 'AB-',
        Gender: 'Female',
        Notes: 'Medical Assistance',
    },
    {
        Id: 6,
        Name: 'Richa',
        Text: 'Richa',
        DOB: new Date(1989, 10, 29),
        Mobile: '+91 0000000000',
        Email: 'richa46@mail.com',
        Address: 'Address Line 1, City, Country',
        enite: 'Monday',
        DepartmentName: 'financeAdvisor',
        BloodGroup: 'B+',
        Gender: 'Female',
        Notes: 'Finance Assistance',
    },
    {
        Id: 7,
        Name: 'Veer',
        Text: 'Veer',
        DOB: new Date(1989, 10, 29),
        Mobile: '+91 0000000000',
        Email: 'veer@mail.com',
        Address: 'Address Line 1, City, Country',
        enite: 'Monday',
        DepartmentName: 'counselling',
        BloodGroup: 'B+',
        Gender: 'Male',
        Notes: 'Counselling required',
    }
];

export const waitingList: Record<string, any>[] = [
    {
        Id: 1,
        Name: 'Prem',
        StartTime: new Date(2022, 7, 3, 8, 30),
        EndTime: new Date(2022, 7, 3, 9, 30),
        enite: 'Sudden loss of vision',
        DepartmentName: 'GENERAL',
        Treatment: ' ',
        DepartmentId: 1,
        userId: 1
    }, {
        Id: 2,
        Name: 'Mihir',
        StartTime: new Date(2022, 7, 4, 8, 30),
        EndTime: new Date(2022, 7, 4, 10, 30),
        enite: 'Bone Fracture',
        DepartmentName: 'financeAdvisor',
        Treatment: ' ',
        DepartmentId: 5,
        userId: 2
    }, {
        Id: 3,
        Name: 'Raghav',
        StartTime: new Date(2022, 7, 4, 9, 30),
        EndTime: new Date(2022, 7, 4, 10, 30),
        enite: 'Skin Hives',
        DepartmentName: 'DERMATOLOGY',
        Treatment: ' ',
        DepartmentId: 3,
        userId: 3
    }, {
        Id: 4,
        Name: 'Jasprit',
        StartTime: new Date(2022, 7, 3, 11, 0),
        EndTime: new Date(2022, 7, 3, 12, 30),
        enite: 'Frequent urination',
        DepartmentName: 'DIABETALOGY',
        Treatment: ' ',
        DepartmentId: 5,
        userId: 4
    }, {
        Id: 5,
        Name: 'Lalitha',
        StartTime: new Date(2022, 7, 3, 11, 0),
        EndTime: new Date(2022, 7, 3, 12, 30),
        enite: 'Muscle weakness',
        DepartmentName: 'CA, ACCA',
        Treatment: ' ',
        DepartmentId: 2,
        userId: 5,
    }, {
        Id: 6,
        Name: 'Richa',
        StartTime: new Date(2022, 7, 3, 11, 0),
        EndTime: new Date(2022, 7, 3, 12, 30),
        enite: 'Shortness of breath',
        DepartmentName: 'counselling',
        Treatment: '   ',
        DepartmentId: 6,
        userId: 6
    }, {
        Id: 7,
        Name: 'Richa',
        StartTime: new Date(2022, 7, 3, 8, 30),
        EndTime: new Date(2022, 7, 3, 9, 30),
        enite: 'Sudden loss of vision',
        DepartmentName: 'GENERAL',
        Treatment: ' ',
        DepartmentId: 1,
        userId: 6
    }, {
        Id: 8,
        Name: 'Lalitha',
        StartTime: new Date(2022, 8, 4, 8, 30),
        EndTime: new Date(2022, 8, 4, 10, 30),
        enite: 'Bone Fracture',
        DepartmentName: 'financeAdvisor',
        Treatment: ' ',
        DepartmentId: 5,
        userId: 5,
    }, {
        Id: 9,
        Name: 'Jasprit',
        StartTime: new Date(2022, 7, 4, 9, 30),
        EndTime: new Date(2022, 7, 4, 10, 30),
        enite: 'Skin Hives',
        DepartmentName: 'DERMATOLOGY',
        Treatment: ' ',
        DepartmentId: 3,
        userId: 4
    },
];

export const hospitalData: Record<string, any>[] = [
    {
        Id: 1000,
        Name: 'Mihir',
        StartTime: new Date(2022, 7, 5, 10, 30),
        EndTime: new Date(2022, 7, 5, 11, 30),
        enite: 'Bone Fracture',
        DepartmentName: 'financeAdvisor',
        DepartmentId: 5,
        agencyId: 5,
        userId: 2,
        Notes: 'Finance Assistance'
    }, {
        Id: 1001,
        Name: 'Jasprit',
        StartTime: new Date(2022, 7, 3, 11, 0),
        EndTime: new Date(2022, 7, 3, 12, 0),
        enite: 'Needs legal advice related to new projects',
        DepartmentName: 'GENERAL',
        DepartmentId: 1,
        agencyId: 3,
        userId: 4,
        Notes: 'Needs legal advice related to new projects'
    }, {
        Id: 1002,
        Name: 'Mary',
        enite: 'Skin Problem',
        DepartmentName: 'generalmedicine',
        DepartmentId: 1,
        StartTime: new Date(2022, 7, 2, 10, 0),
        EndTime: new Date(2022, 7, 2, 11, 0),
        agencyId: 1,
        userId: 5,
        Notes: 'User has skin problem and needs a agency.'
    }, {
        Id: 1003,
        Name: 'Prem',
        enite: 'Feeling very hungry - even though you are eating',
        DepartmentName: 'FINANCEADVISOR',
        DepartmentId: 5,
        StartTime: new Date(2022, 7, 9, 10, 0),
        EndTime: new Date(2022, 7, 9, 11, 0),
        agencyId: 5,
        userId: 1,
        Notes: 'Financial Advisor needed as soon as possible.'
    }, {
        Id: 1004,
        Name: 'Richa',
        enite: 'Skin care treatment',
        DepartmentName: 'FINANCEADVISOR',
        DepartmentId: 5,
        StartTime: new Date(2022, 7, 7, 10, 0),
        EndTime: new Date(2022, 7, 7, 11, 0),
        agencyId: 4,
        userId: 2,
        Notes: 'Finance Assistance'
    }, {
        Id: 1005,
        Name: 'Raghav',
        enite: 'FINANCEADVISOR  ',
        DepartmentName: 'FINANCEADVISOR',
        DepartmentId: 1,
        StartTime: new Date(2022, 7, 7, 13, 30),
        EndTime: new Date(2022, 7, 7, 14, 0),
        agencyId: 1,
        userId: 3,
        Notes: 'Finance Assistance'
    }, {
        Id: 1006,
        Name: 'Richa',
        enite: 'Left Arm Fracture',
        DepartmentName: 'financeAdvisor',
        DepartmentId: 5,
        StartTime: new Date(2022, 7, 7, 16, 0),
        EndTime: new Date(2022, 7, 7, 17, 0),
        agencyId: 5,
        userId: 6,
        Notes: 'Finance Assistance'
    }, {
        Id: 1007,
        Name: 'Raghav',
        enite: 'Chest Pain',
        DepartmentName: 'counselling',
        DepartmentId: 6,
        StartTime: new Date(2022, 7, 13, 11, 0),
        EndTime: new Date(2022, 7, 13, 11, 30),
        agencyId: 7,
        userId: 2,
        Notes: 'Counselling required'
    }, {
        Id: 1008,
        Name: 'Mihir',
        enite: 'Skin Care Treatment',
        DepartmentName: 'counselling',
        DepartmentId: 6,
        StartTime: new Date(2022, 7, 13, 9, 0),
        EndTime: new Date(2022, 7, 13, 10, 0),
        agencyId: 4,
        userId: 2,
        Notes: 'Counselling required'
    }, {
        Id: 1009,
        Name: 'Raghav',
        enite: '  Treatment',
        DepartmentName: 'counselling',
        DepartmentId: 6,
        StartTime: new Date(2022, 7, 10, 14, 0),
        EndTime: new Date(2022, 7, 10, 16, 0),
        agencyId: 1,
        userId: 3,
        Notes: 'Counselling required'
    }, {
        Id: 1010,
        Name: 'Raghav',
        enite: 'Bone Problem',
        DepartmentName: 'financeAdvisor',
        DepartmentId: 5,
        StartTime: new Date(2022, 7, 11, 11, 0),
        EndTime: new Date(2022, 7, 11, 13, 0),
        agencyId: 5,
        userId: 3,
        Notes: 'Financial assistance and security required'
    }, {
        Id: 1011,
        Name: 'Raghav',
        enite: 'General  ',
        DepartmentName: 'financeAdvisor',
        DepartmentId: 5,
        StartTime: new Date(2022, 7, 1, 11, 0),
        EndTime: new Date(2022, 7, 1, 12, 0),
        agencyId: 5,
        userId: 3,
        Notes: 'No special notes'
    }, {
        Id: 1012,
        Name: 'Jasprit',
        enite: 'Complete loss of sensation',
        DepartmentName: 'CA, ACCA',
        DepartmentId: 2,
        StartTime: new Date(2022, 7, 1, 16, 30),
        EndTime: new Date(2022, 7, 1, 17, 30),
        agencyId: 2,
        userId: 4,
        Notes: 'Counselling required for income tax filing'
    }, {
        Id: 1013,
        Name: 'Prem',
        StartTime: new Date(2022, 7, 5, 13, 0),
        EndTime: new Date(2022, 7, 5, 14, 0),
        enite: 'Health  ',
        DepartmentName: 'CA, ACCA',
        DepartmentId: 2,
        agencyId: 2,
        userId: 1,
        Notes: 'Needs assistance for income tax filing'
    }, {
        Id: 1014,
        Name: 'Raghav',
        StartTime: new Date(2022, 7, 5, 16, 0),
        EndTime: new Date(2022, 7, 5, 17, 0),
        enite: 'Eye and Spectacles  ',
        DepartmentName: 'CA, ACCA',
        DepartmentId: 2,
        agencyId: 3,
        userId: 3,
        Notes: 'No special notes'
    }, {
        Id: 1015,
        Name: 'Mihir',
        enite: 'Money investment advice',
        DepartmentName: 'FINANCEADVISOR',
        DepartmentId: 5,
        StartTime: new Date(2022, 7, 6, 12, 0),
        EndTime: new Date(2022, 7, 6, 13, 0),
        agencyId: 5,
        userId: 2,
        Notes: 'Money investment advice'
    }, {
        Id: 1016,
        Name: 'Raghav',
        enite: 'Kidney enite',
        DepartmentName: 'FINANCEADVISOR',
        DepartmentId: 5,
        StartTime: new Date(2022, 7, 6, 18, 0),
        EndTime: new Date(2022, 7, 6, 18, 30),
        agencyId: 6,
        userId: 3,
        Notes: 'Financial advice required'
    }, {
        Id: 1017,
        Name: 'Jasprit',
        enite: 'Gastroparesis',
        DepartmentName: 'FINANCEADVISOR',
        DepartmentId: 5,
        StartTime: new Date(2022, 7, 4, 14, 0),
        EndTime: new Date(2022, 7, 4, 14, 30),
        agencyId: 6,
        userId: 4,
        Notes: 'Money investment assistance'
    }, {
        Id: 1018,
        Name: 'Prem',
        enite: 'Sleep apnea',
        DepartmentName: 'FINANCEADVISOR',
        DepartmentId: 5,
        StartTime: new Date(2022, 7, 4, 12, 0),
        EndTime: new Date(2022, 7, 4, 13, 0),
        agencyId: 6,
        userId: 1,
        Notes: 'Assistance for financial decisions'
    }, {
        Id: 1019,
        Name: 'Mihir',
        enite: 'Vision problems',
        DepartmentName: 'FINANCEADVISOR',
        DepartmentId: 5,
        StartTime: new Date(2022, 7, 4, 10, 0),
        EndTime: new Date(2022, 7, 4, 11, 0),
        agencyId: 5,
        userId: 2,
        Notes: 'Loans and related information'
    }, {
        Id: 1020,
        Name: 'Mihir',
        enite: 'Life Insurance required',
        DepartmentName: 'FINANCEADVISOR',
        DepartmentId: 5,
        StartTime: new Date(2022, 7, 2, 12, 0),
        EndTime: new Date(2022, 7, 2, 13, 0),
        agencyId: 6,
        userId: 2,
        Notes: 'Life Insurance required'
    }, {
        Id: 1021,
        Name: 'Raghav',
        StartTime: new Date(2022, 7, 6, 10, 0),
        EndTime: new Date(2022, 7, 6, 11, 0),
        enite: 'Bone Fracture',
        DepartmentName: 'financeAdvisor',
        DepartmentId: 5,
        agencyId: 5,
        userId: 3,
        Notes: 'Finance assistance required'
    }, {
        Id: 1022,
        Name: 'Lalitha',
        StartTime: new Date(2022, 7, 2, 15, 0),
        EndTime: new Date(2022, 7, 2, 15, 30),
        enite: 'Left Arm Fracture',
        DepartmentName: 'financeAdvisor',
        DepartmentId: 5,
        agencyId: 5,
        userId: 5,
        Notes: 'Money investment and risk inormation needed.'
    }, {
        Id: 1023,
        Name: 'Mihir',
        enite: 'Rapid heartbeat',
        DepartmentName: 'counselling',
        DepartmentId: 6,
        StartTime: new Date(2022, 7, 6, 14, 0),
        EndTime: new Date(2022, 7, 6, 14, 30),
        agencyId: 7,
        userId: 2,
        Notes: 'Need counselling'
    }, {
        Id: 1024,
        Name: 'Raghav',
        enite: 'Lightheadedness',
        DepartmentName: 'counselling',
        DepartmentId: 6,
        StartTime: new Date(2022, 7, 4, 17, 30),
        EndTime: new Date(2022, 7, 4, 18, 30),
        agencyId: 7,
        userId: 3,
        Notes: 'Counselling required'
    }, {
        Id: 1026,
        Name: 'Mihir',
        enite: 'Racing heartbeat',
        DepartmentName: 'counselling',
        DepartmentId: 6,
        StartTime: new Date(2022, 7, 6, 15, 30),
        EndTime: new Date(2022, 7, 6, 16, 0),
        agencyId: 7,
        userId: 2,
        Notes: 'Immediate counselling required'
    }, {
        Id: 1027,
        Name: 'Mihir',
        enite: 'Heart Problem',
        DepartmentName: 'counselling',
        DepartmentId: 6,
        StartTime: new Date(2022, 7, 3, 14, 0),
        EndTime: new Date(2022, 7, 3, 14, 30),
        agencyId: 7,
        userId: 2,
        Notes: 'Counselling required immediately'
    }, {
        Id: 1028,
        Name: 'Mihir',
        enite: 'Dizziness',
        DepartmentName: 'FINANCEADVISOR',
        DepartmentId: 5,
        StartTime: new Date(2022, 7, 5, 19, 0),
        EndTime: new Date(2022, 7, 5, 19, 30),
        agencyId: 6,
        userId: 2,
        Notes: 'Feeling of risk in money investment'
    }];

export const specializationData: Record<string, any>[] = [
    { DepartmentId: 1, Id: 'generalmedicine', Text: 'General Medicine', Color: '#F538B2' },
    { DepartmentId: 2, Id: 'CA, ACCA', Text: 'CA, ACCA', Color: '#33C7E8' },
    { DepartmentId: 3, Id: 'dermatology', Text: 'Dermatology', Color: '#916DE4' },
    { DepartmentId: 5, Id: 'financeAdvisor', Text: 'Finance Advisor', Color: '#60F238' },
    { DepartmentId: 6, Id: 'counselling', Text: 'counselling', Color: '#F29438' },
    { DepartmentId: 7, Id: 'law', Text: 'Law', Color: '#F29438' },
    { DepartmentId: 8, Id: 'Psychiatrist', Text: 'Psychiatrist', Color: '#F29438' },
];

export const experienceData: Record<string, any>[] = [
    { Id: '1+ years', Text: '1+ years' },
    { Id: '2+ years', Text: '2+ years' },
    { Id: '5+ years', Text: '5+ years' },
    { Id: '10+ years', Text: '10+ years' },
    { Id: '15+ years', Text: '15+ years' },
    { Id: '20+ years', Text: '20+ years' }
];

export const dutyTimingsData: Record<string, any>[] = [
    { Id: 'Shift1', Text: '08:00 AM - 05:00 PM' },
    { Id: 'Shift2', Text: '10:00 AM - 07:00 PM' },
    { Id: 'Shift3', Text: '12:00 AM - 09:00 PM' }
];

export const activityData: Record<string, any>[] = [
    {
        Name: 'Added New Agency',
        Message: 'Success',
        Time: '5 mins ago',
        Type: 'agency',
        ActivityTime: new Date(2022, 7, 8, 9, 0)
    },
    {
        Name: 'Added New Appointment',
        Message: 'Success',
        Time: '5 mins ago',
        Type: 'appointment',
        ActivityTime: new Date(2022, 7, 8, 11, 0)
    },
    {
        Name: 'Added New User',
        Message: 'James Richard for Fever and cold',
        Time: '5 mins ago',
        Type: 'user',
        ActivityTime: new Date(2022, 7, 8, 10, 0)
    },
    {
        Name: 'Added New Appointment',
        Message: 'Success',
        Time: '5 mins ago',
        Type: 'appointment',
        ActivityTime: new Date(2022, 7, 11, 11, 0)
    }
];

// Preference module data

export const timeSlots: Record<string, any>[] = [
    { Value: 10, Text: '10 mins' },
    { Value: 20, Text: '20 mins' },
    { Value: 30, Text: '30 mins' },
    { Value: 60, Text: '60 mins' },
    { Value: 120, Text: '120 mins' }
];

export const startHours: Record<string, any>[] = [
    { Value: '08:00', Text: '8:00 AM' },
    { Value: '09:00', Text: '9:00 AM' },
    { Value: '10:00', Text: '10:00 AM' },
    { Value: '11:00', Text: '11:00 AM' },
    { Value: '12:00', Text: '12:00 AM' }
];

export const endHours: Record<string, any>[] = [
    { Value: '16:00', Text: '4:00 PM' },
    { Value: '17:00', Text: '5:00 PM' },
    { Value: '18:00', Text: '6:00 PM' },
    { Value: '19:00', Text: '7:00 PM' },
    { Value: '20:00', Text: '8:00 PM' },
    { Value: '21:00', Text: '9:00 PM' }
];

export const views: Record<string, any>[] = [
    { Value: 'Day', Text: 'Daily' },
    { Value: 'Week', Text: 'Weekly' },
    { Value: 'Month', Text: 'Monthly' }
];

export const colorCategory: Record<string, any>[] = [
    { Value: 'Departments', Text: 'Department Colors' },
    { Value: 'agencys', Text: 'agencys Colors' }
];

export const bloodGroupData: Record<string, any>[] = [
    { Value: 'AB+', Text: 'AB+' },
    { Value: 'A+', Text: 'A+' },
    { Value: 'B+', Text: 'B+' },
    { Value: 'O+', Text: 'O+' },
    { Value: 'AB-', Text: 'AB-' },
    { Value: 'A-', Text: 'A-' },
    { Value: 'B-', Text: 'B-' },
    { Value: 'O-', Text: 'O-' }
];

export const dayOfWeekList: Record<string, any>[] = [
    { Value: 0, Text: 'Sunday' },
    { Value: 1, Text: 'Monday' },
    { Value: 2, Text: 'Tuesday' },
    { Value: 3, Text: 'Wednesday' },
    { Value: 4, Text: 'Thursday' },
    { Value: 5, Text: 'Friday' },
    { Value: 6, Text: 'Saturday' }
];

// shift wise block data
export const shift1BlockData = [
    {
        Id: 50,
        Name: 'Off Work',
        StartTime: new Date(2022, 7, 2, 17, 0),
        EndTime: new Date(2022, 7, 2, 21, 0),
        RecurrenceRule: 'FREQ=DAILY;INTERVAL=1;',
        IsAllDay: false,
        IsBlock: true,
        agencyId: [1, 2, 3, 4, 5, 6, 7]
    }
];

export const shift2BlockData = [
    {
        Id: 51,
        Name: 'Off Work',
        StartTime: new Date(2022, 7, 2, 8, 0),
        EndTime: new Date(2022, 7, 2, 10, 0),
        RecurrenceRule: 'FREQ=DAILY;INTERVAL=1;',
        IsAllDay: false,
        IsBlock: true,
        agencyId: [1, 2, 3, 4, 5, 6, 7]
    }, {
        Id: 52,
        Name: 'Off Work',
        StartTime: new Date(2022, 7, 2, 19, 0),
        EndTime: new Date(2022, 7, 2, 21, 0),
        RecurrenceRule: 'FREQ=DAILY;INTERVAL=1;',
        IsAllDay: false,
        IsBlock: true,
        agencyId: [1, 2, 3, 4, 5, 6, 7]
    },
];

export const shift3BlockData = [
    {
        Id: 53,
        Name: 'Off Work',
        StartTime: new Date(2022, 7, 2, 8, 0),
        EndTime: new Date(2022, 7, 2, 12, 0),
        RecurrenceRule: 'FREQ=DAILY;INTERVAL=1;',
        IsAllDay: false,
        IsBlock: true,
        agencyId: [1, 2, 3, 4, 5, 6, 7]
    }
];
